In [1]:
import yt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.axes_grid1 import AxesGrid

:0: FutureWarning: IPython widgets are experimental and may change in the future.


In [8]:
rvir0,rvir02,rvir05,rvir1 = 316.86,294.55,226.32,162.66
fn = "/Volumes/TOSHIBA EXT/r0038/redshift0038"
ds = yt.load(fn,file_style="%s.grid.cpu%%04i")
val, pos = ds.find_max('Density')
rvir = 162.66

yt : [INFO     ] 2016-09-02 18:15:20,895 Parameters: current_time              = 275.041308666
yt : [INFO     ] 2016-09-02 18:15:20,896 Parameters: domain_dimensions         = [128 128 128]
yt : [INFO     ] 2016-09-02 18:15:20,898 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2016-09-02 18:15:20,900 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2016-09-02 18:15:20,901 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2016-09-02 18:15:20,902 Parameters: current_redshift          = 0.999998836835
yt : [INFO     ] 2016-09-02 18:15:20,903 Parameters: omega_lambda              = 0.721
yt : [INFO     ] 2016-09-02 18:15:20,903 Parameters: omega_matter              = 0.279
yt : [INFO     ] 2016-09-02 18:15:20,904 Parameters: hubble_constant           = 0.7
Parsing Hierarchy : 100%|██████████| 44535/44535 [00:03<00:00, 11802.28it/s]
yt : [INFO     ] 2016-09-02 18:15:28,534 Gathering a field list (this may take a moment.)
yt : [INFO     

In [9]:
#pos = [0.40328598,0.47176743,0.46131516]
#rvir = 320.

dp = yt.ProjectionPlot(ds,'x',('gas','density'),center=pos,width=(1000,"kpc"))
cmap = sns.blend_palette(("black","#984ea3","#d73027","darkorange","#ffe34d","#4daf4a","white"), n_colors=60, as_cmap=True)
dp.set_cmap(('gas','density'),cmap)
dp.set_zlim(('gas','density'),5e-6,1e-2)
dp.annotate_sphere(pos, radius=(rvir,'kpc'), circle_args={'color':'white', 'ls':'--', 'lw':2})
dp.hide_axes()
dp.save('density_z1')

yt : [INFO     ] 2016-09-02 18:25:24,483 Projection completed
yt : [INFO     ] 2016-09-02 18:25:24,490 xlim = 0.432869 0.488869
yt : [INFO     ] 2016-09-02 18:25:24,491 ylim = 0.463570 0.519570
yt : [INFO     ] 2016-09-02 18:25:24,496 xlim = 0.432869 0.488869
yt : [INFO     ] 2016-09-02 18:25:24,497 ylim = 0.463570 0.519570
yt : [INFO     ] 2016-09-02 18:25:24,500 Making a fixed resolution buffer of (('gas', 'density')) 800 by 800
yt : [INFO     ] 2016-09-02 18:25:25,233 Saving plot density_z1_Projection_x_density.png


['density_z1_Projection_x_density.png']

In [11]:
tp = yt.ProjectionPlot(ds,'x',('gas','temperature'),weight_field=('gas','density'),center=pos,width=(1000,"kpc"))
cmap = sns.blend_palette(("black","#d73027","darkorange","#ffe34d"), n_colors=50, as_cmap=True)
tp.set_cmap("temperature",cmap)
tp.set_zlim("temperature",1e4,5e6)
tp.annotate_sphere(pos, radius=(rvir,'kpc'), circle_args={'color':'white', 'ls':'--', 'lw':2})
tp.hide_axes()
tp.save('temp_z1')

yt : [INFO     ] 2016-09-02 18:35:29,818 Projection completed
yt : [INFO     ] 2016-09-02 18:35:29,821 xlim = 0.432869 0.488869
yt : [INFO     ] 2016-09-02 18:35:29,822 ylim = 0.463570 0.519570
yt : [INFO     ] 2016-09-02 18:35:29,825 xlim = 0.432869 0.488869
yt : [INFO     ] 2016-09-02 18:35:29,825 ylim = 0.463570 0.519570
yt : [INFO     ] 2016-09-02 18:35:29,827 Making a fixed resolution buffer of (('gas', 'temperature')) 800 by 800
yt : [INFO     ] 2016-09-02 18:35:30,602 Saving plot temp_z1_Projection_x_temperature_density.png


['temp_z1_Projection_x_temperature_density.png']

In [6]:
mp = yt.ProjectionPlot(ds, 'x', ('gas','metallicity'), weight_field=('gas','density'), center=pos, width=(1000,"kpc"))
mp.set_zlim(('gas','metallicity'),1e-4,1e-2)
cmap = sns.blend_palette(("black","#984ea3","#4575b4","#4daf4a","#ffe34d","darkorange"), as_cmap=True)
mp.set_cmap(('gas','metallicity'),cmap)
mp.annotate_sphere(pos, radius=(rvir,'kpc'), circle_args={'color':'white', 'ls':'--', 'lw':2})
mp.hide_axes()
mp.save('metal_z1')

yt : [INFO     ] 2016-09-02 18:14:02,845 Projection completed
yt : [INFO     ] 2016-09-02 18:14:02,847 xlim = 0.444710 0.486710
yt : [INFO     ] 2016-09-02 18:14:02,848 ylim = 0.457550 0.499550
yt : [INFO     ] 2016-09-02 18:14:02,850 xlim = 0.444710 0.486710
yt : [INFO     ] 2016-09-02 18:14:02,851 ylim = 0.457550 0.499550
yt : [INFO     ] 2016-09-02 18:14:02,854 Making a fixed resolution buffer of (('gas', 'metallicity')) 800 by 800
yt : [INFO     ] 2016-09-02 18:14:03,465 Saving plot metal_z05_Projection_x_metallicity_density.png


['metal_z05_Projection_x_metallicity_density.png']

In [ ]:
mp = yt.ProjectionPlot(ds, 'x', ('gas','metallicity'), weight_field=('gas','density'), center=pos, width=(1000,"kpc"))
mp.set_zlim(('gas','metallicity'),1e-2,1)
cmap = sns.blend_palette(("black","#984ea3","#4575b4","#4daf4a","#ffe34d","darkorange"), as_cmap=True)
mp.set_cmap(('gas','metallicity'),cmap)
mp.annotate_sphere(pos, radius=(rvir,'kpc'), circle_args={'color':'white', 'ls':'--', 'lw':2})
mp.hide_axes()
mp.save('metal_z1_higher')

So multipanels is just not going well and I don't know what the issue is. SO! I'm going to go back to the original strategy of making frbs. It's easy to go directly from the projections but can I make a thin frb in yt3...

In [3]:
thickness = yt.YTQuantity(500., 'kpc')
width = yt.YTQuantity(320.,'kpc')
thickness,width = thickness.in_units('cm'),width.in_units('cm')

thickness = float(thickness.value)/1.10202798453e+26
width = float(width.value)/1.10202798453e+26


In [4]:
axis = 'x'

if axis=='x':
    axis = 0
elif axis=='y':
    axis = 1
elif axis=='z':
    axis = 2
else:
    print 'no correct axis'

center = np.array(pos)
LE,RE = center.copy(),center.copy()
LE[axis] -= thickness/2.0
RE[axis] += thickness/2.0

area_axes = [0,1,2]
i = area_axes.index(axis)
del area_axes[i]

LE[area_axes] -= width/2.0
RE[area_axes] += width/2.0

LE,RE

(array([ 0.39628598,  0.46728743,  0.45683516]),
 array([ 0.41028598,  0.47624743,  0.46579516]))

In [21]:
reg = ds.unit_registry

for un in reg.keys():
    if un.startswith('code_'):
        fmt_tup = (un, reg.lut[un][0], str(reg.lut[un][1]))
        print ("Unit name:      {:<15}\nCGS conversion: {:<15}\nDimensions:     {:<15}\n".format(*fmt_tup))


Unit name:      code_magnetic  
CGS conversion: 0.000918623200201
Dimensions:     sqrt((mass))/(sqrt((length))*(time))

Unit name:      code_time      
CGS conversion: 6.81554201096e+14
Dimensions:     (time)         

Unit name:      code_temperature
CGS conversion: 1.0            
Dimensions:     (temperature)  

Unit name:      code_pressure  
CGS conversion: 6.71529282277e-08
Dimensions:     (mass)/((length)*(time)**2)

Unit name:      code_mass      
CGS conversion: 3.43762402761e+48
Dimensions:     (mass)         

Unit name:      code_velocity  
CGS conversion: 1617626299.16  
Dimensions:     (length)/(time)

Unit name:      code_length    
CGS conversion: 1.10202798453e+26
Dimensions:     (length)       

Unit name:      code_density   
CGS conversion: 2.5685055429e-30
Dimensions:     (mass)/(length)**3

Unit name:      code_metallicity
CGS conversion: 1.0            
Dimensions:     1              



In [ ]:
obj = ds.proj('Density','x',center=center)#,weight_field=weight_field)
#obj = ds.proj(fields,'x',weight_field,center,region)

Parsing Hierarchy : 100%|██████████| 29485/29485 [00:01<00:00, 16827.27it/s]
yt : [INFO     ] 2016-09-02 13:00:25,781 Gathering a field list (this may take a moment.)


In [5]:
region = ds.region(center,LE,RE)
obj2 = ds.proj('Temperature','x',data_source=region,weight_field='Density')    
    
    #obj = pf.h.proj(axis,fields,source=region,center=center,weight_field=weight_field)
        #frb = obj.to_frb(width,resolution,center=center)

Parsing Hierarchy : 100%|██████████| 29485/29485 [00:01<00:00, 16374.81it/s]
yt : [INFO     ] 2016-09-02 13:02:26,408 Gathering a field list (this may take a moment.)
yt : [INFO     ] 2016-09-02 13:04:09,214 Projection completed


In [9]:
resolution = [800,800]
frb_out = obj2.to_frb(width,resolution,center=center)

In [35]:
frb = np.array(frb_out['Temperature'])
frb.shape

print region.fcoords.shape
print LE,RE
print region.fcoords[:,0].min(),region.fcoords[:,0].max()



(14744990, 3)
[ 0.39628598  0.46728743  0.45683516] [ 0.41028598  0.47624743  0.46579516]
0.396286010742 code_length 0.410285949707 code_length


In [19]:
cmap = sns.blend_palette(("black","#d73027","darkorange","#ffe34d"), n_colors=50, as_cmap=True)
plt.imshow(np.log10(frb),interpolation='none',cmap=cmap,vmin=4,vmax=6.7)
#plt.cmap("temperature",cmap)
#plt.set_zlim("temperature",1e4,5e6)
plt.colorbar()
#tp.annotate_sphere(pos, radius=(320.,'kpc'), circle_args={'color':'white', 'ls':'--', 'lw':2})
plt.show()

In [18]:
plt.close()

In [39]:
dir(region.quantities)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'angular_momentum_vector',
 'bulk_velocity',
 'center_of_mass',
 'data_source',
 'extrema',
 'keys',
 'max_location',
 'min_location',
 'sample_at_max_field_values',
 'sample_at_min_field_values',
 'spin_parameter',
 'total_mass',
 'total_quantity',
 'weighted_average_quantity',
 'weighted_variance']

In [3]:
print pos

[ 0.39342117  0.46570969  0.47854996] code_length


In [4]:
print rvir


226.32
